# This defines the version of vagrant
Vagrant.configure(2) do |config|
	# Specifying the box we wish to use
	config.vm.box = "boxomatic/centos-stream-8"
	(1..3).each do |i|
		# Defining VM properties
		config.vm.define "machine#{i}" do |node|
			node.vm.network "private_network", ip: "192.168.0.#{100+i}"
			#node.vm.network "public_network", ip: "10.0.2.#{100+i}", bridge: "enp0s3"
			node.ssh.insert_key = false
			# node.ssh.host = "192.168.0.#{100+i}"
			# node.ssh.port = "22"
			node.vm.hostname = "machine#{i}"
			node.vm.provider "virtualbox" do |vb|
				vb.name = "machine#{i}"  
			end
		end
	end
end
